---
- name: make sure first two nodes are seeds
  set_fact: 
    cassandra_cluster_seeds: "{% for host in groups['seeds'] %}{{hostvars[host]['ansible_host']}},{% endfor %}"

- name: Print cassandra_cluster_seeds
  debug:
    msg: "{{ cassandra_cluster_seeds }}"


- name: make sure cassandra service env path is existing
  file:
    path: "{{ cassandra_service_environment_path }}"
    state: directory
    mode: '0755'

- name: generate cassandra service env file
  template:
    src: cassandra.service.env.j2
    dest: "{{ cassandra_service_environment_path }}/{{ cassandra_service_environment_file }}"
  notify:  restart cassandra

- name: sync cassandra config file cassandra.yaml
  template:
    src: cassandra.yaml.j2
    dest: "/etc/cassandra/cassandra.yaml"
  notify:  restart cassandra

- name: setup cassandra service
  template:
    src: cassandra.service.j2
    dest: /etc/systemd/system/cassandra.service
    owner: root
    group: root
    mode: '0644'
  notify:  restart cassandra

- name: maek sure cassandra service is enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - cassandra.service
