---
# handlers file for ansible-role-cassandra
- name: restart cassandra
  command: /bin/true
  notify:
    - Cassandra | reload systemd
    - Cassnadra | reload cassandra.service
#    - Docker | reload docker
#    - Docker | wait for docker

- name: Cassandra | reload systemd
  systemd:
    daemon_reload: true

- name: Cassandra | reload cassandra.service
  service:
    name: cassandra.service
    state: restarted

- name: Cassandra | wait for cassandra
  command: "{{ docker_bin_dir }}/docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0
